### ISSUE TITLE
[Idea] 1.18.2 port?

### ISSUE THREAD

**Issue by TheFurryDevil** [Traben-0/Entity_Model_Features#73] opened 2023-07-06 19:55 UTC
It would be fantastic if we could get a port for 1.18.2 some time, especially since ETF exists. Unless there is a reason it wasn't done yet, sorry if I missed that. I guess I could try porting Fresh Animations to JEMS...

**Comment by Traben-0** [comment] 2023-07-12 07:58
duplicate of #41

**Closed by Traben-0** 2023-07-12 07:58 UTC
Labels: enhancement
