### ISSUE TITLE
[Bug] Shulker Box loads while Shulker does not

### ISSUE THREAD

**Issue by RyanCR03** [Traben-0/Entity_Model_Features#26] opened 2023-04-19 06:28 UTC
**Describe the bug**
Shulker box model works fine while Shulker model does not take effect

**To Reproduce**
1. Download [resources.zip](https://github.com/Traben-0/Entity_Model_Features/files/11277787/resources.zip)
2. Spawn Shulker, Place Shulker box

**Expected behavior**
Block entities are not meant to work, shulker boxes are block entities, while shulkers are not

**(please complete the following information):**
 - Minecraft Version: 1.19.4
 - EMF version 0.2.5
 - Does the issue persist with only EMF installed? Yes

**Comment by Traben-0** [comment] 2023-04-19 06:32
resources.zip is empty for me just a folder and pack.mcmeta

I have an idea of the cause however I will update you here when i resolve this issue

**Comment by RyanCR03** [comment] 2023-04-19 21:38
this one should work

[resources.zip](https://github.com/Traben-0/Entity_Model_Features/files/11277787/resources.zip)

**Comment by punctdan** [comment] 2023-06-28 23:26
I just got the same issue. I grabbed only shulker and shulker box entities from [CMM resource pack](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiG-_Gjjuf_AhWN7LsIHUZ1CgEQFnoECA0QAQ&url=https%3A%2F%2Fwww.curseforge.com%2Fminecraft%2Ftexture-packs%2Fcute-mob-models-resource-pack&usg=AOvVaw1D5taTVQn8TIkDd-m8djnK&opi=89978449) to illustrate. They work fine when I'm using OptiFine 1.19.4. But something the complete opposite happens with EMF. With EMF, shulker entity does not use a custom model at all (only vanilla model) while shulker box entity uses a custom model and even animates it as if it is the true shulker model.

![image](https://github.com/Traben-0/Entity_Model_Features/assets/46677171/4cdcd4fd-7dea-4e89-978d-d8dd78175c18)

**Comment by punctdan** [comment] 2023-09-18 22:51
This issue seems to be fixed in EMF 1.0.

**Comment by Traben-0** [comment] 2023-09-19 00:15
It is still broken for 1.19 forge, I intend to fix for v1.0.2

**Comment by Traben-0** [comment] 2023-11-16 07:22
I believe I did yes

**Closed by Traben-0** 2023-11-16 07:22 UTC
Labels: bug
