### ISSUE TITLE
[Bug - models] model variation doesn't work without a default model

### ISSUE THREAD

**Issue by PastaLaPasta** [Traben-0/Entity_Model_Features#153] opened 2023-12-21 17:38 UTC
**Describe the bug**
I'm setting up a personal pack with zombie variants that uses the thinner arms that the player can use. They are a part of the same folders the regular arms use in Blockbench, but when the pack is loaded with EMF those second set of arms will not work (the normal ones will though).

**List and link to broken resourcepacks**
[Here](https://drive.google.com/file/d/18lLlzsUSGC3ro5AcyOupn5csLNY4RZoA/view?usp=sharing).

**Expected behavior**
The model should load the same way it does with OF.

**Screenshots**
An example can be seen here: https://imgur.com/a/FvYASXG

**(please complete the following information):**
 - Minecraft Version: 1.20.1
 - EMF version: 1.2

**Comment by PastaLaPasta** [comment] 2023-12-21 18:42
Alright, I've put the model and textures into a zip archive and linked it in the main post.

Since I'm redistributing it, I'll add this disclaimer: this is a modification of somebody else's pack rather than my entirely original textures. The original is an older version of the pack found [here](https://www.curseforge.com/minecraft/texture-packs/mickey-joes-relatively-improved-default).

**Comment by PastaLaPasta** [comment] 2023-12-21 20:59
That did indeed work. Thank you.

Programming is strange.

**Comment by Traben-0** [comment] 2023-12-21 22:45
Hmm that shouldn't be necessary after v1.2 I'll have to double check there isn't some check canceling things left in

**Comment by Traben-0** [comment] 2024-01-03 14:04
i've identified the cause should be fixed next update

**Comment by Traben-0** [comment] 2024-01-19 01:26
:)

**Closed by Traben-0** 2024-01-19 01:26 UTC
Labels: bug
